plugins {
	id 'java'
}
repositories {
	maven {
		url = 'https://repo.runelite.net'
		content {
			includeGroupByRegex("net\\.runelite.*")
		}
	}
	mavenCentral()
}
dependencies {
	compileOnly 'net.runelite:client:latest.release'
}
group = 'com.chartplotter'
tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
	options.release.set(11)
	options.compilerArgs.addAll(['-Xlint:all,-classfile,-processing', '-Werror'])
}
