displayName=Chart Plotter
author=Dazuz
description=Collision-aware sailing navigation helper for viewing your current and projected courses and planning ordered trips through one or more destinations.
tags=sailing,sail,path,pathing,plotting,plot,chart,charting,navigation,navigating,nav,map,route,routing,course,ship,boat,minimap,worldmap,destination
version=2026-08-22
plugins=com.chartplotter.ChartPlotterPlugin
build=standard
