displayName=Chart Plotter
author=Dazuz
description=A Chart Plotter helper too to assist you with all your sailing chart plotting needs.
tags=sailing,sail,path,pathing,plotting,plot,chart,charting,navigation,navigating,nav
version=2026-05-22
plugins=com.chartplotter.ChartPlotterPlugin
build=standard