displayName=Chart Plotter
author=Dazuz
description=Collision-aware sailing navigation helper for viewing your current and projected courses and planning a route to a destination.
tags=sailing,sail,path,pathing,plotting,plot,chart,charting,navigation,navigating,nav,map,route,routing,course,ship,boat,minimap,worldmap,destination
version=2026-06-14
plugins=com.chartplotter.ChartPlotterPlugin
build=standard